# Loki + Promtail без постоянного хранилища
loki:
  enabled: true
  persistence:
    enabled: false
  service:
    type: ClusterIP
promtail:
  enabled: true
  daemonset:
    enabled: true
  config:
    clients:
      - url: http://loki:3100/loki/api/v1/push
    positions:
      filename: /tmp/positions.yaml
    scrape_configs:
      - job_name: kubernetes-pods
        pipeline_stages:
          - docker: {}
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: ['__meta_kubernetes_namespace']
            target_label: namespace
          - source_labels: ['__meta_kubernetes_pod_name']
            target_label: pod
          - source_labels: ['__meta_kubernetes_pod_container_name']
            target_label: container

          # ✅ ADDED: удобный label app
          - source_labels: ['__meta_kubernetes_pod_label_app']
            target_label: app