apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: consumer-servicemonitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: consumer          # метка сервиса consumer
  endpoints:
  - targetPort: 8000         # вместо port: 8000
    interval: 30s
  namespaceSelector:
    matchNames:
    - otus