image:
  tag: latest   # repository удалён

kafka:
  bootstrap: kafka:9092
  topic: input

minio:
  endpoint: http://minio:9000
  accessKey: minio
  secretKey: minio123

config:
  tps: "1000"
  dataset: "a.csv"