name: Cleanup Infrastructure

on:
  workflow_dispatch:
    inputs:
      deploy_run_id:
        description: 'ID запуска workflow Deploy, чьи ресурсы нужно удалить (например, 1234567890)'
        required: true
        type: number

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Terraform
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          # wget https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
          wget https://releases.hashicorp.com/terraform/1.8.5/terraform_1.8.5_linux_amd64.zip
          unzip terraform_1.8.5_linux_amd64.zip
          sudo mv terraform /usr/local/bin/

      - name: Download Terraform state from the specified deploy run
        uses: actions/download-artifact@v4
        with:
          name: infra-artifacts-${{ inputs.deploy_run_id }}
          # path: tf/
          path: ./            
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ${{ inputs.deploy_run_id }}

      - name: Terraform Destroy
        env:
          TF_VAR_yc_token:     ${{ secrets.YC_TOKEN }}
          TF_VAR_yc_cloud_id:  ${{ secrets.YC_CLOUD_ID }}
          TF_VAR_yc_folder_id: ${{ secrets.YC_FOLDER_ID }}
        run: |
          # Если state скачан, инициализируем локально (без удалённого бэкенда)
          cd tf
          echo 'disable_signature_verification = true' > no_verify.hcl
          export TF_CLI_CONFIG_FILE="$(pwd)/no_verify.hcl"
          terraform init -reconfigure
          terraform destroy -auto-approve